### ISSUE TITLE
Drag State doesn't update in Firefox

### ISSUE THREAD

**Issue by mtnc** [ls1intum/Apollon#1]
When dragging an entity while not dragging it far enough for it to update its position, the entity retains its opacity as if it is still being dragged, although it was dropped and the mouse click is no longer held.
The problem couldn't be reproduced deterministically and only occurs in Firefox (Version 61.0.1).
It can be fixed if the entity is moved by at least a square of the grid.
![image](https://user-images.githubusercontent.com/13050544/42411218-a2a8fa5a-81f8-11e8-8d2d-0aa84c0a5304.png)
The opacity is dependent on the variable `isDragging` and is set in the file `src/gui/components/Canvas/Entity/index.tsx` in the function `computeContainerStyle()`.

**Comment by jwilland-tum** [comment]
This issue is already fixed in the upcoming v2 release.
