### ISSUE TITLE
[very minor] [UI] Reduce the Actor's vertical Scale by 1 'Box' 

### ISSUE THREAD

**Issue by CommanderStorm** [ls1intum/Apollon#100]
### Describe the bug
When adding an actor to an usecase diagramm, the Alignment of the vertical contactpoint is of by 1/2 'Box', due to the standard height of the actor being an uneven number..

#### To Reproduce
1. Add an Actor to an UseCase Diagramm
2. Connect the Actor to another Object
4. see screenshot above

#### Expected behavior
no crooked arrows

#### Screenshots
<img width="197" alt="Anmerkung 2020-05-09 212510" src="https://user-images.githubusercontent.com/26258709/81483217-c5a77300-923c-11ea-898c-682c3b7ed6b2.png">

### Environment
<details><pre>
 - OS: Windows
 - Browser Chrome
 - Version latest included in Artemis
</pre></details>

**Comment by TobiasPr** [comment]
@CommanderStorm Could you give me more information on this? I was not able to reproduce. You can also use https://apollon.ase.in.tum.de/ which uses the same version that is included in Artemis

Could you show me the svg element in the browser console - similar to my screenshot? For me the polyline element always has exactly 2 points, which should always be displayed as a straight line.

![image](https://user-images.githubusercontent.com/22955066/81661430-64e68900-943c-11ea-8c54-5ee5d420b353.png)

**Comment by CommanderStorm** [comment]
i'm sorry.. 
crooked was not the right term (hindsight is 20:20)
What I really meant is "non-vertical" with crooked
(i.e. something really minor..)

**Comment by TobiasPr** [comment]
Cannot reproduce this, I am always able to find the straight horizontal line to the use cas by moving the actor or the use case
