### ISSUE TITLE
Required interfaces overlap and make it difficult to read

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Apollon#103]
### Describe the bug
The required interface in a component/deloyment diagram has exactly a semicircle however if you have two required interfaces attached on opposite directions on a provided interface it becomes a full circle and makes it hard to see what the actual provided and that the required ones are.

#### To Reproduce
See screenshots, if not reproducable let me know then I'll provide more details

#### Expected behavior
You can clearly see the differences. The solution would be to make the line length shorter to probably one quarter of a circle.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/349c2ff32c49c068a501e1826d68c0e9/raw)](https://gyazo.com/349c2ff32c49c068a501e1826d68c0e9)

**Comment by TobiasPr** [comment]
will be included in Apollon 2.1.1
![image (3)](https://user-images.githubusercontent.com/22955066/83943772-dd075b00-a7fe-11ea-8543-504db7f8ea63.png)
