### ISSUE TITLE
No straight lines on certain component sizes

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Apollon#104]
### Describe the bug
Not able to create a straight line with certain component sizes.

#### To Reproduce
1. Create a component
2. Resize this component to match a hight of 5 small grid boxes and therefore one big box
3. Add a interface an connect it with the component
4. Try to drag it to a straight line

#### Expected behavior
Straight line.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/cdfd5e971af78c331fded37c82d791b1/raw)](https://gyazo.com/cdfd5e971af78c331fded37c82d791b1)
[![Screenshot from Gyazo](https://gyazo.com/e72d007e00ef72f7f6fa05b34f9059c0/raw)](https://gyazo.com/e72d007e00ef72f7f6fa05b34f9059c0)

#### Additional context
This might actually be the issue of #100 
(see second screenshot). This always happens when a resizable UML element has an odd hight and the other one an even height. (Same v.v. and regarding the width).

**Comment by julian-christl** [comment]
However this might be an interesting issue since there is a grid for a reason.

**Comment by TobiasPr** [comment]
It always happens with uneven sizes  in case of component diagrams (and others) and I also guess with use cases, because use cases can only moved 2 units at a time (might apply to other components as well)

**Comment by TobiasPr** [comment]
will be included in next Apollon release
