### ISSUE TITLE
Stereotype brackets shown on empty field in deployment diagram node

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Apollon#110]
### Describe the bug
It's not possible to remove a sterotype from a node within a deployment diagram by leaving the input field empty.

#### To Reproduce
1. Create a node within a deployment diagram
2. Empty the stereotype input field
3. Above the name it still states "<<>>"

#### Expected behavior
"<<>>" is not shown when the field is empty

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/2ecaec33eb0b434078682d962fb98d74/raw)](https://gyazo.com/2ecaec33eb0b434078682d962fb98d74)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.97
</pre></details>

**Comment by TobiasPr** [comment]
Fixed, will go into next apollon release
