### ISSUE TITLE
Required Interface in Component and Deployment Diagrams

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Apollon#112]
### Describe the bug

Unclean representation of multiple required interfaces on an interface in deployment or component diagram

### Motivation
> Everything worked for me as well! 
> 
> I have one suggestions:
> 
> ![image](https://user-images.githubusercontent.com/52030186/84783924-0176ea80-afea-11ea-97ce-9c3f744517fb.png)
> 
> is it possible for 3 or 4 required interfaces to keep the ones across to each other like they are and add an extra space to the other so that it looks like this?
> 
> ![image](https://user-images.githubusercontent.com/52030186/84784369-82ce7d00-afea-11ea-903d-5204afe2df66.png)

> **Usability for interfaces**
> Working as intended however since this only applied when having three required interfaces this means that you still have the issue with two required interfaces.
> It's not a big deal but as you can see in the screenshot the required interface intersects the line from the provided interface (right):
> [![Screenshot from Gyazo](https://camo.githubusercontent.com/4734e970c8ffc14f4ef47c31297a7653ea63c5b0/68747470733a2f2f6779617a6f2e636f6d2f34653061653030326230383263376262303934306432306361623233386139652f726177)](https://gyazo.com/4e0ae002b082c7bb0940d20cab238a9e)

#### To Reproduce

1. Create a component or deployment diagram with an interface
2. add multiple interfaces to one port 

#### Expected behavior

Clean representation

**Comment by TobiasPr** [comment]
after disucssing with @krusche we will currently not invest time in fixing this issue

**Comment by julian-christl** [comment]
Why closing this though? Why not keep it in the backlock until there is time to fix it?

**Comment by minrows** [comment]
Implemented on PR https://github.com/ls1intum/Apollon/pull/263
