### ISSUE TITLE
Activity Diagrams Fork & Join Nodes

### ISSUE THREAD

**Issue by tobiasschamel** [ls1intum/Apollon#113]
### Describe the bug
It is not possible to rescale the fork and join nodes in activity diagrams.

#### To Reproduce

1. Create an Activity Diagram in Apollon
2. Add a join/fork node
3. try to resize it

#### Expected behavior

Length of join/fork node is changed

#### Screenshots

![image](https://user-images.githubusercontent.com/58089908/86596763-10264100-bf9b-11ea-9f4f-8e9014275f56.png)

### Environment

<details><pre>
 - OS: macOs 10.15.5
 - Browser latest Safari Version

 - OS: Win10
 - Browser : Chrome
 - Version  83.0.4103.116 (Official Build) (64-bit)
</pre></details>

**Comment by TobiasPr** [comment]
@tobiasschamel why do you need this feature? Even if it is bigger the fork node has only 4 places to connect to

**Comment by tobiasschamel** [comment]
A year ago, it was possible to model fork/join nodes like this. This just looks way better & increases readability for students & tutors. (Given that the arrows are distributed as shown in the picture [this was the case last year])
![692D25D4-EAA2-40DF-979D-B6A3F5D600A9](https://user-images.githubusercontent.com/58089908/88490652-60daf980-cf9d-11ea-8d9c-b6decd43f11b.jpeg)

**Comment by TobiasPr** [comment]
Sorry, my bad. Apparently there is a special case for fork nodes, so it gets correctly lined up with the activities. I will include this in the next apollon release. I am not sure if we should allow also width resizing of the fork nodes - any opinion on that?
![image](https://user-images.githubusercontent.com/22955066/88491230-e52f7b80-cfa1-11ea-8549-0df7c7250d07.png)

**Comment by tobiasschamel** [comment]
Height only should be fine 👍

**Comment by TobiasPr** [comment]
Done for height only - included in apollon version 2.0.15 and in apollon standalone 0.1.6 which is now deployed at https://apollon.ase.in.tum.de/
