### ISSUE TITLE
Associations of different types draw on top of each other

### ISSUE THREAD

**Issue by flodt** [ls1intum/Apollon#115]
### Describe the bug
With overlapping connections between components in class diagrams, it is possible to have associations with different connection types drawn on top of each other.

This is a non-issue for connections of the same type (e.g. 2x aggregation with overlapping diamonds), but can be problematic when an aggregation connection including the diamond is drawn on top of e. g. a regular association - it makes the association look like an aggregation.

#### To Reproduce

1. Create a class diagram
2. Create three components laid out in a triangle
3. Connect two of them to the third so that the arrows overlap
4. Choose different connection types

#### Expected behavior
Connections of different types do not get drawn on top of each other, but rather offset to the side. The behaviour can sometimes be mitigated by choosing a different orientation/layout of the components, but this is not always practical or possible.

#### Screenshots
See this example:
The GameBoardUI's association arrow is drawn underneath the Player's aggregation diamond, making it unclear what is being modelled here. It looks like both classes are connected via aggregation, when in fact only the Player is.

![Screenshot 2020-07-12 at 14 33 37](https://user-images.githubusercontent.com/11790871/87246279-bb783f80-c44c-11ea-9908-081709985f31.png)

Of course, in this example, we can easily reorder, but this is not always the case.
Expected:
![Screenshot 2020-07-12 at 14 33 50](https://user-images.githubusercontent.com/11790871/87246289-c8952e80-c44c-11ea-8428-b4763c449ab4.png)

### Environment

<details><pre>
 - OS: macOS 10.15.5 Catalina
 - Browser Chrome 83.0.4103.116
</pre></details>

**Comment by krusche** [comment]
I don’t consider this as a bug. If you draw on paper or in other UML drawing tools, you also need to make sure that associations don’t overlap.

The modeler is responsible for something like this and the tool cannot prevent all wrong (edge) cases.
