### ISSUE TITLE
Clipboard item diagram type not checked before pasting

### ISSUE THREAD

**Issue by flodt** [ls1intum/Apollon#120]
### Describe the bug
When copying items via the clipboard and pasting in to a diagram, the type of the item is not checked before inserting it into the document. It is thus possible to paste, for example, `UMLUseCaseActor`s into class diagrams, or `UMLComponent`s into activity diagrams, etc.

#### To Reproduce
1. Create a diagram of any type.
2. Copy one of the elements of the diagram to the clipboard.
3. Create a new diagram of _another type_.
4. Paste the illegal diagram element into the new diagram.

#### Expected behavior
Diagram elements of other types are not pasted.

#### Screenshots
![Screenshot 2020-07-24 at 16 04 11](https://user-images.githubusercontent.com/11790871/88399608-6da5f480-cdc7-11ea-8fde-004060cf4885.png)

### Environment
<details><pre>
 - OS: macOS 10.15 Catalina
 - Browser Chrome 84.0.4147.89
</pre></details>

**Comment by jannismain** [comment]
Actually, I like this "feature". Might result in other issues (like unexpected behaviour of components in foreign diagrams), but as an "escape hatch" to create custom diagrams, it might be useful :-)

**Comment by flodt** [comment]
That's true - it's very practical for creating some more informal, or freely designed models.

Then maybe it would also be nice to choose the components from different diagram types in the sidebar on the fly, rather than when creating the diagram and then being "locked in" to that one type.

**Comment by TobiasPr** [comment]
The focus of Apollon is on simplicity and not to rebuild advanced tools like draw.io, star-uml, etc. . We do not want to overwhelm inexperienced users with too many choices. I see the potential here for inexperienced users to mix up elements of different diagrams and thereby creating wrong models, but I am happy to discuss if it makes sense to include a more advanced mode, in which this is possible.

@krusche what is your opinion on this?

**Comment by TobiasPr** [comment]
Implemented a filter which allows only elements of the same diagram type to be pasted
