### ISSUE TITLE
Cannot delete multiple components using keyboard-only input

### ISSUE THREAD

**Issue by jannismain** [ls1intum/Apollon#122]
### Describe the bug
When trying to delete multiple component using keyboard-only input (DELETE/BACKSPACE key), it only deletes the currently selected component. When it is deleted, the previous component looks like it is in focus but cannot be deleted using DELETE/BACKSPACE.

#### To Reproduce
Tested within communication diagram, should be the same across all diagrams

1. Add component (e.g. class)
2. Duplicate component (I'm using CMD+C and CMD+V
3. Delete duplicate (I'm using DELETE/BACKSPACE)
4. Try to delete original (again using DELETE/BACKSPACE)

although the original component is highlighted after the duplicate has been deleted, it cannot be deleted using the keyboard. I have to click the component before I can delete it. I assume, this is due to incorrect focus / focus not being updated after deletion.

#### Expected behavior
When hitting DELETE/BACKSPACE multiple times, components should be deleted one after one. The order might be the order in which they were in focus last.

#### Screenshots
![apollon-delete-focus-bug-480p](https://user-images.githubusercontent.com/14290527/88475955-d959a000-cf34-11ea-9404-ffaab0f8ee1c.gif)

### Environment
<details><pre>
 - OS: macOS 10.15.5 (19F101)
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)
</pre></details>

**Comment by TobiasPr** [comment]
The issue here is, that the element is actually not selected. You are just hovering about the element which becomes the front element after you deleted the former element which was in front of it. So you actually did not select the element. You can test that by moving the cursor away after having the element which you want to delete selected, see screencast
![1](https://user-images.githubusercontent.com/22955066/89050475-179af900-d353-11ea-8dfe-b76032e6d45b.gif)

**Comment by jannismain** [comment]
Yes, you are right, this solves the problem with the supposedly "wrong selection". But don't you agree, that after deletion, the next element should be selected automatically instead of having no active selection?

**Comment by TobiasPr** [comment]
I am not sure about this, because the person will not need the selection in 95% of the cases, because there is no way to switch to other elements using keyboard only. Therefore, I don't think it has that much of a benefit to the users.
