### ISSUE TITLE
Timestamp in "Load Diagram" not displayed correctly for long diagram names

### ISSUE THREAD

**Issue by jannismain** [ls1intum/Apollon#123]
### Describe the bug
Timestamp in "Load Diagram" not displayed correctly for long diagram names

#### To Reproduce
1. Create new diagram with long name
2. Click on 'File' - 'Load'

#### Screenshots
![image](https://user-images.githubusercontent.com/14290527/88477321-6e619680-cf3f-11ea-8a36-abe1c4b530ad.png)

### Environment

<details><pre>
 - OS: macOS 10.15.5 (19F101)
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)
</pre></details>

**Comment by TobiasPr** [comment]
This should be fixed in Apollon Standalone Version 0.1.8. Too long texts are now truncated
![image](https://user-images.githubusercontent.com/22955066/89100006-e58da380-d3f3-11ea-8d8e-292bb7fd3faa.png)
