### ISSUE TITLE
Add support for Petri Nets

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Apollon#127]
### Is your feature request related to a problem?
A few courses cover modeling with Petri nets, which currently needs to be done by pen and paper. It would be great if Petri nets could be modeled directly in Artemis (Apollon).

Example:
<img src="https://user-images.githubusercontent.com/15248220/90228315-4a92c180-de16-11ea-9ed9-4347b1da40f8.png" width="50%">

### Describe the solution you'd like
Petri-nets only consists of 3 components:
* places (dt. Stellen): circle containing markers. Markers should be indicated by black dots. If the number of markers exceeds a threshold value (maybe ~5), a number instead of dots should be displayed. The max. number of markers inside is determined by a capacity that is indicated by a number written nearby the circle. Adjusting markers and capacities should be implemented by a number input. The default capacity depends on the type of the Petri net. For boolean Petri nets, the capacity is fixed to 1, for Petri nets over natural numbers the default value is infinite. The type of the Petri net should be selectable (maybe a checkbox or dropdown menu in the editor).
* transitions: a simple rectangle, accepting in and outgoing arcs
* arcs: Connectors between places and transitions. Arcs are characterized by multiplicities (contrary to UML, there is only one multiplicity per arc). The default multiplicity is 1 and doesn't need to be displayed in this case.

Places and transitions should support the addition of comments (see red text in the example).

Further semantics are extensively described in the literature and the internet. 

Although the example uses different colors, a black and white version with only the comments displayed in another color would be the preferred realization.

### Additional context
We only require basic support for Petri nets over natural numbers and boolean Petri nets. Advanced semantics, like colored Petri nets, are not required (at least not by our lecture).

**It would be great if this feature could be realized until mid-November 2020**

**Comment by TobiasPr** [comment]
@Garfield96 my first implementation would look like this:
![image](https://user-images.githubusercontent.com/22955066/90618471-57e1ee80-e210-11ea-9826-3a5be6421f2a.png)

For the sake of consistency with the other diagrams, I kept the coloring to black and white. - I will think about a solution to the coloring of the different element types.

Please be aware, that we currently do not support any kind of formula symbols as text input. Would that be a requirement for you?

**Comment by Garfield96** [comment]
@TobiasPr This looks already great. I would recommend making the tokens a little bit smaller so that they will not touch each other.

I would consider symbols as nice-to-have but its not a requirement.

**Comment by TobiasPr** [comment]
@Garfield96 I included your feedback and deployed a new version to the standalone version to [Apollon](https://apollon.ase.in.tum.de/) which includes a beta version of petri nets, so you can test out the new diagram type. Any feedback is welcome

**Comment by Garfield96** [comment]
@TobiasPr Thank you. I tested it and it worked fine. The last feature missing in order to use it is support for capacities and multiplicities.

**Comment by TobiasPr** [comment]
Updated once more, looks like this now
![image](https://user-images.githubusercontent.com/22955066/90732564-938dbe80-e2cb-11ea-96c9-3194c2daedc1.png)

I did not constraint the amount of tokens in a place to the capacity. In my opinion, that's the responsibility of the student / modeler. 

I am unsure about whether I chose a good depiction of the capacity for places, since I couldn't find any online
For adding multiplicity, you can double click an arc and enter the number (note - free text is also allowed)

**Comment by TobiasPr** [comment]
both issues will be fixed in next release
