### ISSUE TITLE
`Dark mode`: Aggregation and Composition indistinguishable in UML Class Diagram

### ISSUE THREAD

**Issue by fh314** [ls1intum/Apollon#230]
### Describe the bug
When using the modeling editor to create class diagrams in dark mode, aggregations and compositions seem indistinguishable 

#### To Reproduce
1. Go to a modeling exercise
2. Create an aggregation between two classes
3. Create a composition between two classes

#### Expected behavior
Both types of associations should be easily distinguishable

#### Screenshots
![agg](https://user-images.githubusercontent.com/29736922/167484942-a79be151-f8dd-47a0-abf5-60f46d9dc7c1.PNG)
![comp](https://user-images.githubusercontent.com/29736922/167484948-df18a433-ca65-4162-9a75-34a848638cc8.PNG)

### Environment
<details><pre>
 - OS: Windows 10 Pro
 - Browser Chrome
</pre></details>

**Comment by krusche** [comment]
Duplicate which was already fixed. Will be shipped in the next Artemis release
