### ISSUE TITLE
Can't export anymore and after I try I can't load other files

### ISSUE THREAD

**Issue by CamelotMacaw** [ls1intum/Apollon#233]
### Describe the bug

After using Apollon for a lengthy period of time, export didn't work anymore for a certain class diagram (I tried png, pdf and json). I couldn't load other files either. I closed Apollon and opened it again. Loading was possible again and I was able to export other diagrams, but as soon as I tried to export the class diagram I was originally working on again, loading became impossible once more and, of course, the diagram wasn't downloaded.

#### To Reproduce

Link to the diagram: https://apollon.ase.in.tum.de/XS5umkUDDD2rQh07WiiI?view=GIVE_FEEDBACK

1. Work several hours on class diagram
2. try to export (doesn't work)
3. try to load other file (doesn't work)
4. reload Apollon (2. & 3. persist)
5. restart Browser, reopen Apollon (2. &  3. persist)
6. I don't know what the initial cause was, sorry

#### Expected behavior
Export downloads file and doesn't impact other functionality

#### Screenshots
![image](https://user-images.githubusercontent.com/91760131/169597758-f764c762-07b5-4b26-b239-8d344b8bfd70.png)

### Environment

<details><pre>
</pre></details>

Windows; Google Chrome, 101.0.4951.67

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Can you provide a screenshot of the diagram and a link to it so we can experience the issue as well?

**Comment by CamelotMacaw** [comment]
I wanted to, actually, but this is work for the EIST project homework, so I don't know if it's technically allowed. Is it alright if I send it to you via Zulip?

**Comment by CamelotMacaw** [comment]
> Can you provide a screenshot of the diagram and a link to it so we can experience the issue as well?

I wanted to, actually, but this is work for the EIST project homework, so I don't know if it's technically allowed. Is it alright if I send it to you via Zulip?

**Comment by bensofficial** [comment]
I can reproduce the problem. It does not work with the link provided by @CamelotMacaw nor with another example (also shared with me). At least for me it works fine when I create a new chart.

As shown in the screencast, everything works until I download the diagram as a png file (there is an uncaught error). After that, the downloads (even those that worked before) and the import no longer work.

But after a reload it works again.

https://user-images.githubusercontent.com/66966223/172542388-fe87ebf3-8ca8-42ce-93f0-00af34024f6a.mp4
