### ISSUE TITLE
Component Diagram Provided Interface Connection has White Triangles

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Apollon#251]
See the following image:

![image](https://user-images.githubusercontent.com/11130248/179945898-35139584-b24d-4cab-8566-fd828b557ec4.png)

Does not happen with "Dependency" or "Required Interface" relations in a component diagram.
I am fairly confident this is a recent (past year) regression.

Apollon version 1.5.0 (on the standalone site) with Chromium-based Browser (Vivaldi) as well as Firefox.

**Comment by TizianDippold** [comment]
I have the same problem, using Google Chrome.

Apollon version 1.5.0 on the standalone site aswell.

![apollonbug](https://user-images.githubusercontent.com/92391589/180058535-53fbd106-b66a-4884-9ada-2d7714fe73f2.png)
