### ISSUE TITLE
Unsaved changes not recognised when dismissing popover

### ISSUE THREAD

**Issue by jwilland-tum** [ls1intum/Apollon#28]
#### Current behaviour

If a popover contains unsaved changes, like a new attribute or method for UML class elements, and the user dismisses the popover by clicking anywhere outside the popover, the changes are not saved.

#### Expected behaviour

Save the changes on dismissing the popover.

#### Environment

Apollon 2.0.0-rc.4

**Comment by jwilland-tum** [comment]
Currently, we listen on the blur event of the input element to save changes. Apparently, there seems to be a bug in react that prevents the blur event from firing when the element is removed from the DOM tree (https://github.com/facebook/react/issues/12363).
To solve this issue we are currently investigating workarounds.

**Comment by TobiasPr** [comment]
bugfix in `bugfix/unsaveg_changes_dismissed_in_popover` waiting for more tests before integrating the fix

**Comment by TobiasPr** [comment]
integrated today, will be included in the next release
