### ISSUE TITLE
Toggle Stereotype Visibility

### ISSUE THREAD

**Issue by farisd16** [ls1intum/Apollon#361]
### Problem
In a Component diagram, stereotypes can't be removed from Components and Subsystems, which may present additional clutter. Same goes for Components and Nodes in a Deployment diagram.

### Solution
A new button could be added to the edit popup of the mentioned UML elements. The picture below shows exactly where. This button could have the text/icon "<< >>" inside of it, to indicate it is linked to the stereotype. When the stereotype is visible, the button is active and has a darker background. Otherwise, the button is not active and the background is transparent. Upon clicking the button, visibility of the stereotype is changed.

![stereotype-toggle-proposal](https://github.com/ls1intum/Apollon/assets/63470556/2c8ffa7b-db9e-4a4b-a7c1-ab4881bb9136)

**Comment by FelixTJDietrich** [comment]
Sounds good to me 👍 
Are there any other toggle buttons in Apollon somewhere, maybe you can copy the style from there. Otherwise I think you can start implementing it.
