### ISSUE TITLE
Darkmode with Aggregation/Composition

### ISSUE THREAD

**Issue by latnino** [ls1intum/Apollon#382]
When turning Darkmode on, the Aggreagations get the dark background and appears like a Composition and vice versa with the white color fill.
![image](https://github.com/user-attachments/assets/5ba52aa1-6bb8-45a1-b701-101b05dd703f)
![image](https://github.com/user-attachments/assets/781cb8f3-b0b8-40c8-8eaf-f9bf2dce0f2a)

**Comment by krusche** [comment]
This is intended. Aggregation vs composition is not about the color. It's about whether the diamond is filled or not

**Comment by krusche** [comment]
I guess the UML standard did not imagine a dark mode when it specified this convention
