### ISSUE TITLE
Patch tracking stops working after editor is recreated / restored

### ISSUE THREAD

**Issue by loreanvictor** [ls1intum/Apollon#383]
### Describe the bug

Patch tracking doesn't work after Apollon Editor is recreated. This happens rarely, but whenever [`Apollon.recreateEditor()`](https://github.com/ls1intum/Apollon/blob/250d16a3aa8150758bd795f9f419c98ceacff6b6/src/main/apollon-editor.ts#L498-L522) is called (for example as a consumer needs to trigger a recreation, or the editor needs to be restored due to some error), then the patcher will not be provided.

#### To Reproduce
1. Create an instance of `ApollonEditor` and subscribe to patches (e.g. using [`subscribeToAllModelChangePatches()`]()https://github.com/ls1intum/Apollon/blob/250d16a3aa8150758bd795f9f419c98ceacff6b6/src/main/apollon-editor.ts#L317-L319 method).
2. Test that you do indeed get patches when things change.
3. Invoke `recreateEditor()` on said instance somehow (you can for example provide debug access to it and call it in browser console).
4. You won't get patches anymore.

#### Expected behavior
Patch tracking should still work after `recreateEditor()` is invoked.

#### Additional context

This can be easily fixed by adding `patcher: this.patcher` to [line 515](https://github.com/ls1intum/Apollon/blob/250d16a3aa8150758bd795f9f419c98ceacff6b6/src/main/apollon-editor.ts#L515).

**Comment by loreanvictor** [comment]
@egenerse

**Comment by egenerse** [comment]
solved with this pr https://github.com/ls1intum/Apollon/pull/384
