### ISSUE TITLE
[Bugfix]: Feedback Icons are rendered at wrong position

### ISSUE THREAD

**Issue by jwilland-tum** [ls1intum/Apollon#70]
Currently, the feedback icons are rendered at the top right corner of the bounding box of an element. This leads to bad positioning of icons for relationships. See https://github.com/ls1intum/Artemis/issues/445 for more details.

**Comment by Khalphion** [comment]
I like the changes for the associations, but now the icons are visually placed in a weird spot for classes:

![image](https://user-images.githubusercontent.com/10117554/61954202-99c24600-afb8-11e9-9844-9d1a02f1a32b.png)

The old placement (next to each element, right floating) was better in this case.
