### ISSUE TITLE
Methods and Attributes not added when pressing enter

### ISSUE THREAD

**Issue by SteffenDE** [ls1intum/Apollon#79]
Caused by https://github.com/ls1intum/Apollon/commit/cdb97e16460a63bb45e862c597877639444dcd0e#r34443788.

This was one issue I had this morning with the L13E03: Adding new methods and attributes to a UML Class does not work when pressing enter. 

Browser: Safari and Chrome on macOS Catalina and Mojave.

**Comment by jwilland-tum** [comment]
Thank you for your investigation! Tried to fix another issue with the `Next Assessment` button on the assessment with this change. Reverted the linked line and found another fix for the button.

#80
