### ISSUE TITLE
[UI] Minor UI Issues

### ISSUE THREAD

**Issue by jannismain** [ls1intum/Apollon#88]
I hope you don't mind me reporting tiny nitpicks like this. :-)

When trying out Apollon, I notices the following minor UI issues:

<img width="1364" alt="Screenshot 2020-02-22 at 1 32 15 PM" src="https://user-images.githubusercontent.com/14290527/75092715-d1a76100-557a-11ea-8525-04b1dd66fcbb.png">

1. The content of the "Diagram Type" Dropdown goes past its boundary. 
I would recommend extending the sidebar or using `...` to indicate overflowing content.
2. Image for "Schnittstelle" overlays "Komponente"
3. "Readonly" checkbox seems very close to the Mode Dropdown Menu.
Also, would write [read-only](https://www.merriam-webster.com/dictionary/read-only)

Best Regards,
Jannis

**Comment by TobiasPr** [comment]
@jannismain thank you for reporting the issue and sorry for the late reply. I will have a look into it :)
