### ISSUE TITLE
Underscores are not rendered correctly under object names in Firefox

### ISSUE THREAD

**Issue by alexsteinh** [ls1intum/Apollon#99]
### Describe the bug
Underscores under object names are being overlapped by the characters above. This only occures in Firefox.

#### To Reproduce
1. Switch the Diagram Type to 'Object Diagram'

#### Expected behavior
Underscores are completly visible.

#### Screenshots
![grafik](https://user-images.githubusercontent.com/40439946/81333702-429fe480-90a5-11ea-8a81-1d2a25ad8411.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76.0
</pre></details>

**Comment by TobiasPr** [comment]
@alexsteinh Firefox is currently not one of our main suported browsers. Please use chrome for now. We might change that in the future when we have more resources
